// This file is auto-generated by @hey-api/openapi-ts

export const $FeatureFlag = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.078Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.078Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        role: {
            type: 'string',
            enum: ['SUPER_ADMIN', 'ADMIN', 'USER'],
            example: 'USER'
        },
        json: {
            type: 'array',
            items: {
                type: 'string',
                enum: ['users:read:*', 'users:write:*', 'users:write:create', 'users:write:update', 'users:write:delete', 'users:write:archive', 'users:write:restore', 'products:read:*']
            },
            example: ['users:read:*', 'users:write:*']
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'role', 'json']
} as const;

export const $User = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.077Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.077Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        email: {
            type: 'string',
            format: 'email',
            example: 'bossROD@gmail.com'
        },
        first_name: {
            type: 'string',
            nullable: true,
            example: 'boss'
        },
        last_name: {
            type: 'string',
            nullable: true,
            example: 'ROD'
        },
        mobile_no: {
            type: 'string',
            nullable: true,
            example: '+1234567890'
        },
        role: {
            type: 'string',
            enum: ['SUPER_ADMIN', 'ADMIN', 'USER'],
            example: 'USER'
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'email', 'first_name', 'last_name', 'mobile_no', 'role']
} as const;

export const $Group = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.080Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.080Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        name: {
            type: 'string',
            example: 'Weekend Trip'
        },
        description: {
            type: 'string',
            nullable: true,
            example: 'Group for our weekend trip expenses'
        },
        split_type: {
            type: 'string',
            enum: ['EQUAL', 'PERCENTAGE', 'EXACT'],
            example: 'EQUAL'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            example: '123e4567-e89b-12d3-a456-426614174000'
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'name', 'description', 'split_type', 'owner_id']
} as const;

export const $GroupMember = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.079Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.079Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        percentage_share: {
            type: 'number',
            nullable: true,
            example: 25.5
        },
        exact_share: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    nullable: true
                },
                {
                    nullable: true
                }
            ],
            example: '50.75'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            example: '123e4567-e89b-12d3-a456-426614174001'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            example: '123e4567-e89b-12d3-a456-426614174002'
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'percentage_share', 'exact_share', 'group_id', 'user_id']
} as const;

export const $GroupExpense = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.078Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.078Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        amount: {
            type: 'string',
            example: '150.75'
        },
        expense_date: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                },
                {
                    nullable: true
                }
            ],
            example: '2025-04-06T15:43:16.078Z'
        },
        description: {
            type: 'string',
            nullable: true,
            example: 'Dinner at restaurant'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            example: '123e4567-e89b-12d3-a456-426614174001'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            example: '123e4567-e89b-12d3-a456-426614174002'
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'amount', 'expense_date', 'description', 'group_id', 'owner_id']
} as const;